volumes:
  postgres_data:
    driver: local

x-keycloak-environment: &keycloak-environment
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: password
  KC_DB: postgres
  # See postgres JDBC URL parameters: https://jdbc.postgresql.org/documentation/head/connect.html
  KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak?ApplicationName=keycloak
  KC_DB_USERNAME: keycloak
  KC_DB_PASSWORD: password
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
  KC_HOSTNAME_STRICT_HTTPS: "true"
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KC_LOG_LEVEL: com.twogenidentity.keycloak:debug,org.keycloak.authentication:debug,org.keycloak.transaction:error,org.keycloak.transaction:error,org.keycloak.transaction:error,org.hibernate:error,INFO
#  KC_FEATURES: account3
  KC_PROXY: edge
  DEBUG: "true"
  DEBUG_PORT: "*:8787"

services:
  postgres:
    image: postgres:11
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 35432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    container_name: keycloak
    command: 
      - start-dev 
      - --import-realm
    environment:
      << : *keycloak-environment
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 2s
      retries: 15           
    ports:
      - 8080:8080
      - 8443:8443
      - 8787:8443
    volumes:  
     - $PWD/keycloak/realm-export-bank.json:/opt/keycloak/data/import/realm-export-bank.json
     - $PWD/keycloak/themes:/opt/keycloak/themes
     - $PWD/keycloak/extensions/keycloak-webauthn-conditional-mediation.jar:/opt/keycloak/providers/keycloak-webauthn-conditional-mediation.jar  
    depends_on:
      - postgres